export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_CONFLICT = 'REGISTER_CONFLICT';
export const SERVER_ERROR = 'SERVER_ERROR';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
